apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-dep
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: ghcr.io/hotio/sonarr:release
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "1005"
        - name: PGID
          value: "1005"
        ports:
        - containerPort: {{ .Values.sonarr.port }}
        volumeMounts:
        - name: servarr
          mountPath: /data
          subPath: data
        - name: servarr
          mountPath: /config
          subPath: config/sonarr
        - name: old
          mountPath: /oldmedia
      volumes:
      - name: servarr
        nfs:
          server: nfs.markdavison.kiwi
          path: /mnt/ironwolf/servarr
      - name: old
        nfs:
          server: nfs.markdavison.kiwi
          path: /mnt/ironwolf/media
