apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wildcard-markdavison-kiwi-es
  labels:
    app: servarr
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wildcard-markdavison-kiwi
  data:
  - secretKey: tls.key
    remoteRef:
      key: kv/data/wildcard
      property: key
  - secretKey: tls.crt
    remoteRef:
      key: kv/data/wildcard
      property: crt