apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr-dep
  labels:
    app: readarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  readarr
  template:
    metadata:
      labels:
        app: readarr
    spec:
      containers:
      - name: readarr
        image: cr.hotio.dev/hotio/readarr
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "1005"
        - name: PGID
          value: "1005"
        ports:
        - containerPort: {{ .Values.readarr.port }}
        volumeMounts:
        - name: servarr
          mountPath: /data
          subPath: data
        - name: servarr
          mountPath: /config
          subPath: config/readarr
      volumes:
      - name: servarr
        nfs:
          server: nfs.markdavison.kiwi
          path: /mnt/ironwolf/servarr