apiVersion: v1
kind: Service
metadata:
  name: readarr-svc
  labels:
    app: readarr
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.readarr.port }}
    protocol: TCP
  selector:
    app: readarr