apiVersion: v1
kind: Service
metadata:
  name: overseerr-svc
  labels:
    app: overseerr
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.overseerr.port }}
    protocol: TCP
  selector:
    app: overseerr