apiVersion: v1
kind: Service
metadata:
  name: prowlarr-svc
  labels:
    app: prowlarr
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.prowlarr.port }}
    protocol: TCP
  selector:
    app: prowlarr